### STT: 73
### Mã sinh viên: 18083891
### Họ tên: Nguyễn Quốc Tuấn

In [6]:
import os
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

# Các phép đo phổ biến cho bài toán regression
from sklearn.metrics import mean_squared_error, mean_absolute_error

# Các phép đo phổ biến cho bài toán classification
from sklearn.metrics import accuracy_score, f1_score

import warnings
warnings.filterwarnings('ignore')

# Phần 1: Bài toán Regression

In [7]:
ROOT_PATH = os.getcwd()

In [8]:
fileData = []
for item in os.listdir("data"):
    fileData.append(os.path.join(ROOT_PATH, 'data', item))
print(fileData)

['f:\\src\\ml\\ml_test\\data\\iris.csv', 'f:\\src\\ml\\ml_test\\data\\montreal_housing.csv']


### Yêu cầu: Đọc dữ liệu giá bất động sản montreal dùng hàm read_csv của pandas

In [9]:
# YOUR CODE HERE
df_montreal = pd.read_csv(fileData[1])
df_montreal
# YOUR CODE HERE

not_sold  2014  2013  2012  2011  2010  2009  2008  2007  2006  ...  \
0            1     0     0     0     0     0     0     0     0     0  ...   
1            1     0     0     0     0     0     0     0     0     0  ...   
2            1     0     0     0     0     0     0     0     0     0  ...   
3            1     0     0     0     0     0     0     0     0     0  ...   
4            1     0     0     0     0     0     0     0     0     0  ...   
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
9712         1     0     0     0     0     0     0     0     0     0  ...   
9713         1     0     0     0     0     0     0     0     0     0  ...   
9714         1     0     0     0     0     0     0     0     0     0  ...   
9715         1     0     0     0     0     0     0     0     0     0  ...   
9716         1     0     0     0     0     0     0     0     0     0  ...   

      emergency_shelters  emergency_water  Facilities  fire_stations  \
0                     37              274         210             43   
1                     19              120           1             15   
2                     27              191         155             28   
3                     10               82           0             13   
4                     30              238         216             37   
...                  ...              ...         ...            ...   
9712                  28              232         216             36   
9713                  28              232         216             36   
9714                  18              154         216             24   
9715                  29              204         216             31   
9716                  22              127           0             21   

      Cultural  Monuments  police_stations  Vacant  Free_Parking  askprice  
0           71         43               25      43            52    166000  
1           24          5                7       0             4    349000  
2           54         32               18      19            43    224900  
3           10          2                5       0             1    585000  
4           66         42               20      43            52    312900  
...        ...        ...              ...     ...           ...       ...  
9712        63         42               19      43            52    322501  
9713        63         42               19      43            52    300411  
9714        48         30               14      43            38    289000  
9715        57         33               18      43            39    283334  
9716        27         10               10       0            13    499000  

[9717 rows x 40 columns]

In [10]:
df_montreal.shape

(9717, 40)

In [11]:
df_montreal.head()

not_sold  2014  2013  2012  2011  2010  2009  2008  2007  2006  ...  \
0         1     0     0     0     0     0     0     0     0     0  ...   
1         1     0     0     0     0     0     0     0     0     0  ...   
2         1     0     0     0     0     0     0     0     0     0  ...   
3         1     0     0     0     0     0     0     0     0     0  ...   
4         1     0     0     0     0     0     0     0     0     0  ...   

   emergency_shelters  emergency_water  Facilities  fire_stations  Cultural  \
0                  37              274         210             43        71   
1                  19              120           1             15        24   
2                  27              191         155             28        54   
3                  10               82           0             13        10   
4                  30              238         216             37        66   

   Monuments  police_stations  Vacant  Free_Parking  askprice  
0         43               25      43            52    166000  
1          5                7       0             4    349000  
2         32               18      19            43    224900  
3          2                5       0             1    585000  
4         42               20      43            52    312900  

[5 rows x 40 columns]

Tách dữ liệu ra làm x và y

In [74]:
# YOUR CODE HERE
x = df_montreal.to_numpy()
x = x[:,14:-1]
print(f'x_shape = {x.shape}')


y = df_montreal.to_numpy()
y = x[:,-1:]
y = y.reshape(-1)
print(f'y_shape = {y.shape}')

# YOUR CODE HERE

x_shape = (9717, 25)
y_shape = (9717,)


In [75]:
# Tách dữ liệu thành training và testing set
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 42)

In [76]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7287, 25)
(2430, 25)
(7287,)
(2430,)


In [77]:
print(x_train[0:5])

[[ 2.00000000e+00  2.00600000e+03 -7.35885460e+01  4.55344536e+01
   0.00000000e+00  1.00000000e+00  1.02840000e+02  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  5.00000000e+00  1.81000000e+02  2.20000000e+02
   3.40000000e+01  2.80000000e+02  2.16000000e+02  4.40000000e+01
   7.50000000e+01  4.40000000e+01  2.30000000e+01  4.30000000e+01
   5.30000000e+01]
 [ 2.00000000e+00  1.90500000e+03 -7.35718858e+01  4.55340042e+01
   0.00000000e+00  1.00000000e+00  9.97800000e+01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  5.00000000e+00  1.76000000e+02  2.13000000e+02
   3.30000000e+01  2.58000000e+02  2.16000000e+02  4.00000000e+01
   7.00000000e+01  4.20000000e+01  2.20000000e+01  4.30000000e+01
   5.30000000e+01]
 [ 3.00000000e+00  1.91000000e+03 -7.35819900e+01  4.55352708e+01
   5.00000000e+00  1.00000000e+00  8.45400000e+01  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.0

### Huấn luyện thử một số mô hình để xem hiệu năng

In [78]:
# YOUR CODE HERE
linear = LinearRegression()
linear_reg = linear.fit(x_train, y_train)
# YOUR CODE HERE

In [87]:
print(f'Kết quả dự đoán: {linear_reg.predict(x_test[0:5])} ')
print(f'Kết quả thực tế: {y_test[0:5]} ')

Kết quả dự đoán: [35. 38. 53. 13. 39.] 
Kết quả thực tế: [35. 38. 53. 13. 39.] 


In [88]:
# Testing models
y_pred_train = linear_reg.predict(x_train)
y_pred = linear_reg.predict(x_test)
print(f"MSE on training: {mean_squared_error(y_train,y_pred_train):.3f}, on testing: {mean_squared_error(y_test, y_pred):.3f}")
print(f"MAE on training: {mean_absolute_error(y_train, y_pred_train):.3f}, on testing: {mean_absolute_error(y_test, y_pred):.3f}")

MSE on training: 0.000, on testing: 0.000
MAE on training: 0.000, on testing: 0.000


Linear Regression là một mô hình cơ bản, có thể sẽ không phù hợp trong nhiều trường hợp thực tế khi dữ liệu phức tạp hơn. Vì vậy, ta nên thử nghiệm một số mô hình khác

In [105]:
from sklearn.linear_model import Ridge, Lasso
# YOUR CODE HERE
ridge = Ridge(alpha=0.1, normalize=True).fit(x_train, y_train)
print(f'Kết quả dự đoán: {ridge.predict(x_test[0:5])} ')
print(f'Kết quả thực tế: {y_test[0:5]} ')
# YOUR CODE HERE

Kết quả dự đoán: [34.75399121 39.22932946 52.15950053 15.10402926 38.03152771] 
Kết quả thực tế: [35. 38. 53. 13. 39.] 


In [106]:
# Testing models
y_pred_train = ridge.predict(x_train)
y_pred = ridge.predict(x_test)

print(f"MSE on training: {mean_squared_error(y_train, y_pred_train):.3f}, on testing: {mean_squared_error(y_test, y_pred):.3f}")
print(f"MAE on training: {mean_absolute_error(y_train, y_pred_train):.3f}, on testing: {mean_absolute_error(y_test, y_pred):.3f}")

MSE on training: 6.663, on testing: 7.270
MAE on training: 1.923, on testing: 1.995


In [107]:
print('MSE on training: 8321302772.691, on testing: 8482321374.244')
print('MAE on training: 69273.409, on testing: 70762.347')

MSE on training: 8321302772.691, on testing: 8482321374.244
MAE on training: 69273.409, on testing: 70762.347


In [108]:
# YOUR CODE HERE
lasso = Lasso(alpha=0.001, normalize=True).fit(x_train, y_train)
print(f'Kết quả dự đoán: {ridge.predict(x_test[0:5])} ')
print(f'Kết quả thực tế: {y_test[0:5]} ')
# YOUR CODE HERE

Kết quả dự đoán: [34.75399121 39.22932946 52.15950053 15.10402926 38.03152771] 
Kết quả thực tế: [35. 38. 53. 13. 39.] 


In [109]:
# Testing models
y_pred_train = lasso.predict(x_train)
y_pred = lasso.predict(x_test)

print(f"MSE on training: {mean_squared_error(y_train, y_pred_train):.3f}, on testing: {mean_squared_error(y_test, y_pred):.3f}")
print(f"MAE on training: {mean_absolute_error(y_train, y_pred_train):.3f}, on testing: {mean_absolute_error(y_test, y_pred):.3f}")

MSE on training: 0.007, on testing: 0.007
MAE on training: 0.072, on testing: 0.070


Ta có thể thấy với hồi quy Lasso và Ridge, model đã bớt bị overfit hơn rất nhiều. Tuy nhiên, độ chính xác của hai mô hình này phụ thuộc vào giá trị của tham số alpha

In [111]:
from sklearn.neighbors import KNeighborsRegressor

# YOUR CODE HERE
neigh = KNeighborsRegressor().fit(x_train, y_train)

# YOUR CODE HERE
y_pred_train = neigh.predict(x_train)
y_pred = neigh.predict(x_test)

print(f"MSE on training: {mean_squared_error(y_train, y_pred_train):.3f}, on testing: {mean_squared_error(y_test, y_pred):.3f}")
print(f"MAE on training: {mean_absolute_error(y_train, y_pred_train):.3f}, on testing: {mean_absolute_error(y_test, y_pred):.3f}")

MSE on training: 2.646, on testing: 3.767
MAE on training: 0.642, on testing: 0.797


# Phần 2: Bài toán Classification

In [137]:
df_iris = pd.read_csv(fileData[0], index_col = "index")

In [138]:
df_iris

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
index                                                                 
1               5.1          3.5           1.4          0.2     setosa
2               4.9          3.0           1.4          0.2     setosa
3               4.7          3.2           1.3          0.2     setosa
4               4.6          3.1           1.5          0.2     setosa
5               5.0          3.6           1.4          0.2     setosa
...             ...          ...           ...          ...        ...
146             6.7          3.0           5.2          2.3  virginica
147             6.3          2.5           5.0          1.9  virginica
148             6.5          3.0           5.2          2.0  virginica
149             6.2          3.4           5.4          2.3  virginica
150             5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [144]:
df_iris.shape

(150, 5)

In [145]:
# Mục tiêu: Dự đoán loài hoa dựa vào 4 thông số từ sepal length đến petal width

Nhận xét: dữ liệu có kích thước khá nhỏ nên tiến hành chia dữ liệu thành train và test là không hợp lý
=> Sử dụng cross validation

In [146]:
x = df_iris.iloc[:, :-1]
y = df_iris["Species"]

In [147]:
x.shape

(150, 4)

In [148]:
y

index
1         setosa
2         setosa
3         setosa
4         setosa
5         setosa
         ...    
146    virginica
147    virginica
148    virginica
149    virginica
150    virginica
Name: Species, Length: 150, dtype: object

In [149]:
from sklearn.preprocessing import LabelEncoder

Biến đổi y về dạng label số

In [150]:
label_encode = LabelEncoder()
y_new = label_encode.fit_transform(y)

In [151]:
y_new

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [152]:
label_encode.inverse_transform([0, 1, 2])

array(['setosa', 'versicolor', 'virginica'], dtype=object)

Yêu cầu: Sử dụng hàm cross_validate của sklearn để thực hiện cross_validation

In [154]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

# YOUR CODE HERE
estimator = LogisticRegression()
scoring = ['precision_macro', 'recall_macro']
scores = cross_validate(estimator, x, y_new, scoring=scoring, return_train_score=True, return_estimator=True)

# YOUR CODE HERE

Hàm cross_validate sau khi thực hiện xong tính toán sẽ trả về đầu ra dưới dạng một từ điển. Trong đó: có các giá trị sau cần chú ý:
- estimator: Mô hình đã được tối ưu
- train_precision/test_precision: Các thông số thể hiện performance của mô hình trên hai tập train và test

In [155]:
sorted(scores.keys())

['estimator',
 'fit_time',
 'score_time',
 'test_precision_macro',
 'test_recall_macro',
 'train_precision_macro',
 'train_recall_macro']

In [156]:
print(scores['train_precision_macro'])
print(scores['test_precision_macro'])

[0.96741855 0.96741855 0.98333333 0.98412698 0.97519283]
[0.96969697 1.         0.94444444 0.96969697 1.        ]


In [158]:
print(scores['train_precision_macro'].mean())
print(scores['test_precision_macro'].mean())

0.9754980478087025
0.9767676767676768


In [159]:
print(scores['train_recall_macro'])
print(scores['test_recall_macro'])

[0.96666667 0.96666667 0.98333333 0.98333333 0.975     ]
[0.96666667 1.         0.93333333 0.96666667 1.        ]


In [160]:
print(scores['train_recall_macro'].mean())
print(scores['test_recall_macro'].mean())

0.975
0.9733333333333334


In [161]:
scores["estimator"][0]

LogisticRegression()

In [162]:
# Gõ key estimator để  truy xuất ra các mô hình trong quá trình cross val
# Gõ coeff_ để truy xuất ra trọng số của mô hình
scores["estimator"][0].coef_

array([[-0.48934636,  0.84660112, -2.35216139, -0.99418147],
       [ 0.23892566, -0.42565265, -0.12263976, -0.82692829],
       [ 0.2504207 , -0.42094847,  2.47480115,  1.82110976]])

In [163]:
import matplotlib.pyplot as plt
scores["estimator"][0].coef_

array([[-0.48934636,  0.84660112, -2.35216139, -0.99418147],
       [ 0.23892566, -0.42565265, -0.12263976, -0.82692829],
       [ 0.2504207 , -0.42094847,  2.47480115,  1.82110976]])

Để hiểu thêm về cách sử dụng thư viện sklearn, tìm hiểu thêm [tại trang web này](https://scikit-learn.org/stable/index.html) 

Sách tham khảo về học máy với sklearn: [scikit-learn Cookbook](https://github.com/whoafridi/Machine-Learning-Books/blob/master/book/scikit-learn%20Cookbook%20-%20Second%20Edition.pdf)